baseurl = "https://tech.ontheroad.jp/"
#languageCode = "en-us"
languageCode = "ja-JS"
theme = "hugo-theme-terminal"
paginate = 5
defaultContentLanguage="ja"

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.ja]
    title = "Tech Note"
    subtitle = "技術的なトピックを気ままに更新する個人ブログ"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "続きを読む"
    readOtherPosts = "別の記事を読む"

    [languages.ja.params.logo]
      logoText = "Tech Note"
      logoHomeLink = "/"

    [languages.ja.menu]
      [[languages.ja.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.ja.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
